### ISSUE TITLE
Cannot get parser to work...

### ISSUE THREAD

**Issue by WildBillLives** [Kirwiisp/Parser-FBL-servants-of-memory#1]
Perhaps I am doing some step incorrectly but I cannot get the parser to work 
(This is in Foundry v9 build 280, FBL v9.2.2, no modules loaded except FBL Core Game and the parser module).

Step 1) I re-downloaded the latest pdf of 'Servants of Memory' from my DriveThruRPG library.
Step 2) I use Acrobat Reader DC to copy the text from the top of the Table of Contents through page 191 of the document.
Step 3) I open the parser in my Foundry game and paste the text into it, then click the "Go" button. The parser window closes, a folder is created named "Servants of Memory" in the actors directory, but no actors are ever created (I waited up to 5 minutes to make sure).

The following is relevant text from the console, including an error message:

```
Foundry VTT | Retrieved and compiled template modules/fbl-servants-of-memory-npc-parser/templates/import.html
foundry.js:3053 Foundry VTT | Rendering Dialog
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/hud/dialog.html
foundry.js:4660 Foundry VTT | Retrieved and compiled template templates/app-window.html
character-generator.js:101 ///Folder creation/////
foundry.js:4660 Foundry VTT | Retrieved and compiled template modules/fbl-servants-of-memory-npc-parser/templates/text-input.hbs
foundry.js:3053 Foundry VTT | Rendering Dialog
character-generator.js:65 Uncaught (in promise) The requested file storage  does not exist!
      callback | @ | character-generator.js:65
```
I have tried this several times with the same result.  I even started Foundry with Admin privilege but the result was no different.
Thank you.

**Comment by Kirwiisp** [comment]
Hi which version of the module are you using ?

**Comment by Kirwiisp** [comment]
I've identify the problem, should be fix in the next update !

**Comment by WildBillLives** [comment]
Thanks! 

Just an FYI I am using the latest release, v1.3.4
